// app.js: School Test Calendar Logic
// Supabase credentials (replace with your own project values)
const SUPABASE_URL = "https://ohcclcnjqbizebnbling.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oY2NsY25qcWJpemVibmJsaW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MzAzMzcsImV4cCI6MjA3NDQwNjMzN30.GHG-bik_-3I8VbTVIF7PbF_EGCY6JCmG0XmrNV6wJFU";

const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Grade and subject lists
const GRADES = Array.from({ length: 4 }, (_, i) => [
  `${i + 6}a`,
  `${i + 6}b`,
]).flat();
const SUBJECTS = [
  "Matematika",
  "Slovenščina",
  "Angleščina",
  "Fizika",
  "DRUGO"
];
const SUBJECT_COLORS = {
  "Matematika": "#f7b267",
  "Slovenščina": "#a0c4ff",
  "Angleščina": "#ffd6a5",
  "Fizika": "#bdb2ff",
  "DRUGO": "#caffbf",
};

// Grade colors
const GRADE_COLORS = {};
GRADES.forEach((g, i) => {
  // simple autogenerated pastel colors
  const hue = (i * 40) % 360;
  GRADE_COLORS[g] = `hsl(${hue}, 70%, 80%)`;
});

// Inject subject color classes into stylesheet
function injectSubjectStyles() {
  const style = document.createElement("style");
  let css = "";
  for (const [subject, color] of Object.entries(SUBJECT_COLORS)) {
    css += `.subject-${subject
      .toLowerCase()
      .replace(/\s+/g, "-")} { background: ${color}; }\n`;
  }
  style.textContent = css;
  document.head.appendChild(style);
}

// Local cache: { 'YYYY-MM-DD': [test, ...] }
let testCache = {};
let currentGradeFilter = "";

// Utility functions
function getByDate(date) {
  return testCache[date] || [];
}
function addToCache(test) {
  if (!testCache[test.date]) testCache[test.date] = [];
  testCache[test.date].push(test);
}
function removeFromCache(id) {
  for (const date in testCache) {
    testCache[date] = testCache[date].filter((t) => t.id !== id);
  }
}
function updateCache(id, newData) {
  for (const date in testCache) {
    testCache[date] = testCache[date].map((t) =>
      t.id === id ? { ...t, ...newData } : t
    );
  }
}
function clearCache() {
  testCache = {};
}

// CRUD operations
async function fetchTests(start, end) {
  const { data, error } = await supabase
    .from("tests")
    .select("*")
    .gte("date", start)
    .lte("date", end);
  if (error) {
    showToast("Ni uspelo pridobiti preizkusov", true);
    return [];
  }
  clearCache();
  (data || []).forEach(addToCache);
  return data || [];
}

async function createTest(test) {
  const { data, error } = await supabase.from("tests").insert([test]).select();
  if (error) {
    showToast("Ni uspelo dodati preizkusa", true);
    return null;
  }
  addToCache(data[0]);
  return data[0];
}

async function updateTest(id, fields) {
  const { data, error } = await supabase
    .from("tests")
    .update(fields)
    .eq("id", id)
    .select();
  if (error) {
    showToast("Ni uspelo posodobiti preizkusa", true);
    return null;
  }
  updateCache(id, fields);
  return data[0];
}

async function deleteTest(id) {
  const { error } = await supabase.from("tests").delete().eq("id", id);
  if (error) {
    showToast("Ni uspelo izbrisati preizkusa", true);
    return false;
  }
  removeFromCache(id);
  return true;
}

// Toast/snackbar
function showToast(msg, error = false) {
  const toast = document.getElementById("toast");
  toast.textContent = msg + (error ? " (Poskusi znova)" : "");
  toast.classList.add("visible");
  setTimeout(() => toast.classList.remove("visible"), 3000);
}

// Calendar rendering
let calendar;

async function fetchTestsAndFormatEvents(info, successCallback, failureCallback) {
  const start = info.startStr;
  const end = info.endStr;

  const { data, error } = await supabase
    .from("tests")
    .select("*")
    .gte("date", start)
    .lte("date", end);

  if (error) {
    showToast("Ni uspelo pridobiti preizkusov", true);
    failureCallback(error); 
    return;
  }

  // Update cache
  clearCache();
  (data || []).forEach(addToCache);

  // --- FIX: grade filter ---
  let filtered = data || [];
  if (currentGradeFilter) {
    filtered = filtered.filter(t => t.grade === currentGradeFilter);
  }

  const events = filtered.map(test => ({
    id: test.id,
    title: `${test.grade} ${test.subject}${test.description ? ': ' + test.description : ''}`,
    start: test.date,
    allDay: true,
    backgroundColor: GRADE_COLORS[test.grade] || '#ccc',
    borderColor: '#fff',
    extendedProps: { test }
  }));

  successCallback(events);
}

function renderGradeButtons() {
  const container = document.getElementById("gradeButtons");
  container.innerHTML = "";

  GRADES.forEach((g) => {
    const btn = document.createElement("button");
    btn.textContent = g;
    btn.className = "grade-btn";
    btn.onclick = () => {
      currentGradeFilter = g;
      highlightSelectedGrade(g);
      calendar.refetchEvents();
    };
    container.appendChild(btn);
  });

  // Add a "show all" button
  const allBtn = document.createElement("button");
  allBtn.textContent = "Vsi";
  allBtn.className = "grade-btn";
  allBtn.onclick = () => {
    currentGradeFilter = null;
    highlightSelectedGrade(null);
    calendar.refetchEvents();
  };
  container.appendChild(allBtn);
}

function highlightSelectedGrade(selected) {
  document.querySelectorAll(".grade-btn").forEach((btn) => {
    btn.classList.toggle("active", btn.textContent === selected);
  });
}



document.addEventListener("DOMContentLoaded", async () => {
  injectSubjectStyles();
  renderGradeButtons();

  calendar = new FullCalendar.Calendar(document.getElementById("calendar"), {
    locale: 'sl',
    buttonText: {
      today: "Danes"
    },
    initialView: "dayGridMonth",
    dateClick: handleDateClick,
    dayCellDidMount: renderDayCell,
    events: fetchTestsAndFormatEvents,
    eventClick: handleEventClick,
    height: "auto",
    headerToolbar: {
      left: "prev,next today",
      center: "title",
      right: "",
    },
  });
  calendar.render();
});

function renderDayCell(arg) {
  const date = arg.date.toISOString().slice(0, 10);
  let tests = getByDate(date);
  if (currentGradeFilter)
    tests = tests.filter((t) => t.grade === currentGradeFilter);
  if (tests.length) {
    const badgeContainer = document.createElement("span");
    tests.forEach((test) => {
      const badge = document.createElement("span");
      badge.className =
        "subject-badge subject-" +
        test.subject.toLowerCase().replace(/\s+/g, "-");
      badge.title = test.subject;
      badgeContainer.appendChild(badge);
    });
    arg.el.appendChild(badgeContainer);
    if (tests.length > 1) {
      badgeContainer.title = `${tests.length} preizkusov`;
    }
  }
}
function handleDateClick(info) {
  const date = info.dateStr;
  showTooltip(date, info.jsEvent.pageX, info.jsEvent.pageY);
}
function handleEventClick(info) {
  info.jsEvent.stopPropagation();
  const test = info.event.extendedProps.test;
  openTestForm(test.date, test);
}

// Tooltip/popover
function showTooltip(date, x, y) {
  const tooltip = document.getElementById("tooltip");
  tooltip.innerHTML = "";
  tooltip.style.left = x + "px";
  tooltip.style.top = y + "px";
  tooltip.classList.add("visible");
  const tests = getByDate(date).filter(
    (t) => !currentGradeFilter || t.grade === currentGradeFilter
  );
  const title = document.createElement("h3");
  title.textContent = `Preizkusi za ${date}`;
  tooltip.appendChild(title);
  if (tests.length === 0) {
    const empty = document.createElement("div");
    empty.textContent = "Za ta dan ni preizkusov.";
    tooltip.appendChild(empty);
  } else {
    tests.sort(
      (a, b) =>
        a.grade.localeCompare(b.grade) || a.subject.localeCompare(b.subject)
    );
    tests.forEach((test) => {
      const row = document.createElement("div");
      row.className = "test-row";
      row.innerHTML = `<span class="subject-badge subject-${test.subject
        .toLowerCase()
        .replace(/\s+/g, "-")}" title="${test.subject}"></span>
        <strong>${test.grade}</strong> ${test.subject} <span>${
        test.description || ""
      }</span>`;
      const actions = document.createElement("span");
      actions.innerHTML = `<button onclick="editTest('${test.id}','${date}')">Uredi</button>
        <button onclick="deleteTestConfirm('${test.id}','${date}')">Izbriši</button>
        <button onclick="duplicateTest('${test.id}','${date}')">Podvoji</button>`;
      row.appendChild(actions);
      tooltip.appendChild(row);
    });
  }
  const addBtn = document.createElement("button");
  addBtn.textContent = "Dodaj preizkus";
  addBtn.onclick = () => openTestForm(date);
  tooltip.appendChild(addBtn);
}

function hideTooltip() {
  const tooltip = document.getElementById("tooltip");
  if (tooltip) tooltip.classList.remove("visible");
  const form = document.querySelector(".form-modal");
  if (form) form.remove();
}

document.addEventListener("click", (e) => {
  if (
    !e.target.closest("#tooltip") &&
    !e.target.closest(".fc-event") &&
    !e.target.closest(".form-modal")
  ) {
    hideTooltip();
  }
});

// Test form
function openTestForm(date, test = null) {  
  hideTooltip();

  const tooltip = document.getElementById("tooltip");
  const body = document.getElementsByTagName("body")[0];
  const form = document.createElement("form");
  tooltip.classList.add("visible");
  form.className = "form-modal";  
  form.innerHTML = `
    <div class="form-group">
      <label for="grade">Razred</label>
      <select name="grade" id="grade">
        ${GRADES.map(
          (g) =>
            `<option value="${g}"${
              test && test.grade === g ? " selected" : ""
            }>${g}</option>`
        ).join("")}
      </select>
    </div>
    <div class="form-group">
      <label for="subject">Predmet</label>
      <select name="subject" id="subject">
        ${SUBJECTS.map(
          (s) =>
            `<option value="${s}"${
              test && test.subject === s ? " selected" : ""
            }>${s}</option>`
        ).join("")}
      </select>
    </div>
    <div class="form-group">
      <label for="description">Opis</label>
      <textarea name="description" id="description">${
        test ? test.description || "" : ""
      }</textarea>
    </div>
    <div class="form-actions">
      <button type="submit">Shrani</button>
      <button type="button" onclick="hideTooltip()">Prekliči</button>
    </div>
  `;
  form.onsubmit = async (e) => {      
    e.preventDefault();
    const grade = form.grade.value;
    const subject = form.subject.value;
    const description = form.description.value;
    if (!grade || !subject) {
      showToast("Razred in predmet sta obvezna", true);
      return;
    }
    try {
      if (test) {
        const result = await updateTest(test.id, {
          grade,
          subject,
          description,
        });
        if (!result) {
          showToast("Posodobitev ni uspela", true);
          return;
        } else {
          hideTooltip();
          calendar.refetchEvents();
        }
      } else {
        const newTest = { date, grade, subject, description };
        const result = await createTest(newTest);
        if (!result) {
          showToast("Dodajanje ni uspelo", true);
          return;
        } else {
          hideTooltip();
          calendar.refetchEvents();
        }
      }
    } catch (err) {
      showToast("Nepričakovana napaka: " + (err.message || err), true);
      return;
    }
  };
  body.appendChild(form);
}
window.editTest = (id, date) => {
  const test = getByDate(date).find((t) => t.id === id);
  openTestForm(date, test);
};
window.deleteTestConfirm = (id, date) => {
  if (confirm("Izbrišem ta preizkus?")) {
    deleteTest(id).then(() => {
      hideTooltip();
      calendar.refetchEvents();
    });
  }
};
window.duplicateTest = (id, date) => {
  const test = getByDate(date).find((t) => t.id === id);
  openTestForm(date, { ...test, id: undefined });
};


// Help button
const helpBtn = document.getElementById("help-btn");
if (helpBtn) {
  helpBtn.onclick = () => {
    alert(
      "Šolski koledar preizkusov\n\n- Klikni na datum za ogled/dodajanje/urejanje preizkusov.\n- Uporabi filter razreda za prikaz preizkusov za določen razred.\n- Barvne pike prikazujejo predmete.\n- Vsi podatki so shranjeni v Supabase."
    );
  };
}
